
openapi: 3.1.0

info:
  title: Chainlabs API
  description: |-
    ### 
    
    The Chainlabs API provides an automated way of retrieving traced seed addresses, corresponding metadata, and screenshot proofs to replace the monthly manual CSV deliveries.
    
    To retrieve all historical and newly added entities, traces, and screenshots, use the */entities* and */traces* endpoints. To receive updates on modifications or deletions of existing data, use the */sync_entities* and */sync_traces* endpoints. 
  version: 0.1.0

servers:
  - url: "https://chainlabs.wl.r.appspot.com"

security:
  - BearerAuth: []

paths:
  /auth_token:
    post:
      tags:
        - Authentication
      summary: Generate JWT Token
      description: Generate a JWT token by providing the API key and username.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                api_key:
                  type: string
                  description: "API Key required for authentication."
                user_name:
                  type: string
                  description: "Username to generate the token."
              required:
                - api_key
                - user_name
      responses:
        '200':
          description: "JWT token generated successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_token:
                    type: string
                    description: "Generated JWT token"
        '401':
          description: "Invalid API Key"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid API key"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT token for authorization. Use the /auth_token endpoint to generate a token."
